
[window]
dynamic_title = true
opacity = 0.90
option_as_alt = "Both"

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 5
y = 0

[cursor]
blink_interval = 400
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[scrolling]
history = 10000

[env]
TERM = "xterm-256color"
live_config_reload = "true"

[font]
size = 13

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[font.offset]
x = 0
y = 0

[general]
import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux -u"]

