theme = "nightfox"

[editor]
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
character = "╎"
render = true

[keys.normal]
C-n = "goto_next_buffer"
C-p = "goto_previous_buffer"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-h = "jump_view_left"
# S-d = ["find_till_char", "@ret"]
C-m = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"

[keys.normal.space]
q = ":quit"
