theme = "nightfox"

[editor]
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
character = "╎"
render = true

[keys.normal]
C-n = "goto_next_buffer"
C-p = "goto_previous_buffer"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-h = "jump_view_left"
# S-d = ["find_till_char", "@ret"]
# C-m = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.normal.space]
q = ":quit"

[editor.file-picker]
hidden = false
